### ISSUE TITLE
SMS service as chat server

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/smoke#11]
Downloaded Smoke via F-Droid, where to connect to a server?
Why don't you add SMS servers as in Silence SMS encryption app:
https://git.silence.dev/Silence/Silence-Android

**Comment by textbrowser** [comment]
I know you!

And if I do not, but I suspect that I do, OK. But if I do not, although you are a new account, you will require your own service station. SmokeStack, Spot-On, Spot-On-Lite.

Since you ask. SMS is Short Message Service. And this is important, because, it is short. Now, before you blast off, there are versions where segmented messages can be sent and the receiver has to re-assemble them. Similar to TCP.

Anyway, SMS is not free because it requires towers and service providers.

So suppose Smoke had an SMS server as you think that's likely to occur, it would be very expensive to test and/or sustain.

Now, before you go pathological; there are methods of sending SMS through WiFi and/or constructing your own SMS tower facsimile.

In short, good luck.

**Comment by bolzobrazil** [comment]
know? what?
meant not an own SMS server, using the phone provider sms.
however, any phone number is a server via sms.
so will look to install for Smoke an own service station.

**Comment by textbrowser** [comment]
Check out https://github.com/textbrowser/smoke/blob/master/TO-DO before new requests. You are requesting a feature.

https://github.com/textbrowser/smoke/discussions

**Comment by textbrowser** [comment]
Mist will be reviewed in late 2021 and next year. Complicated problem.

**Comment by textbrowser** [comment]
A new activity is not necessary as the Member activity will include an optional telephone number of the respective participant. Messages will be delegated through SMS and / or neighbors. Attachments? Unknown.

**Comment by EmilyJaneWells** [comment]
Hi guys. Im having trouble configuring the smoke app.  I had some difficulties and suffered amnesia but I am regaining them rapidly!!  If someone could respond that would be awesome! 😎

**Comment by textbrowser** [comment]
What sort of problems?
