### ISSUE TITLE
how to generate code ShipHash ?

### ISSUE THREAD

**Issue by huutien98** [textbrowser/smoke#17]
i tried reading the code to learn how to generate the shiphash code but this is quite difficult , can you explain to me the mechanism of generating the shiphash code ? and how the two devices recognize each other through the shiphash code?
Thanks a lot.

**Comment by textbrowser** [comment]
Interesting question. Did you read Smoke.pdf? Smoke instances on devices are not paired. Participants are paired and they're paired using SipHash. See the Smoke Aliases and Smoke Identities sections in the PDF.

Summary: the encryption and signature public keys of two participants are used to pair the two participants. Suppose I am textbrowser@github and you're huuntien98@github. I enter textbrowser@github for my alias and huuntien98@github as a participant. You do this also but reverse the information. At some point the devices go online and the two Smoke instances begin the process of exchanging our public keys. The destination addresses are created using our aliases. My Smoke instance sends my encrypted key bundle using keys generated from your alias. Think of the aliases as public transports which have specific destinations.

**Comment by textbrowser** [comment]
We may also share our SipHash Identities. For example, I may prefer a SipHash Identity and you prefer an alias. I tell you my identity and you tell me your alias. Aliases are easier to remember.

**Comment by textbrowser** [comment]
I selected SipHash because the output (8 bytes) was easier to remember and share. Then aliases emerged. SipHash can be replaced with a better cryptographic hash in the future. The loss would be the easily-remembered outputs. SipHash-128 produces 16 bytes which are difficult to remember.

**Comment by huutien98** [comment]
Yes, I understand . but I still don't understand how the server can recognize which device is connecting to the server? , and the connection between devices . please explain for me .
thank a lot.

**Comment by huutien98** [comment]
I want to learn the messaging mechanism of smoke , how to send packets , encryption , authentication and key management , please explain for me

**Comment by textbrowser** [comment]
Smoke introduced cryptographic routing. Summary: a device connects to a server and sends a public identifier. The server records it and shares this identifier with other clients. Etc. After some time, all servers in a network are aware of this identifier. Cryptographic routing (discovery) is optional.

When you send a message to your friend through an Echo network, each device attempts to determine if the message belongs to it by computing and comparing digests. With cryptographic routing, servers route messages to intended destinations so that the destinations do not have to do this work.

Smoke.pdf details the message structures, encryption, key management, etc.

I'll create a diagram of the general functionality.

**Comment by huutien98** [comment]
I see there is a "connect" function like in the image, it uses SSLSocket , is this how the client connects to the server ?
![image](https://user-images.githubusercontent.com/41584186/144425874-82515677-fae6-42d1-ba59-d558b0f51aa3.png)

**Comment by textbrowser** [comment]
If you're interested in the mechanics, yes. The source is the best place to look at if you need the specifics. :)

**Comment by huutien98** [comment]
yes I do, but I won't be able to fully understand the mechanics of smoke. so if you can, please help me understand it through diagrams for example. thank you and regards

**Comment by huutien98** [comment]
I still don't understand the mechanics of generating the "shiphash" code in smoke . How was it created?

**Comment by textbrowser** [comment]
What do you mean? See SipHash.java.

**Comment by textbrowser** [comment]
What's ShipHash? :D

**Comment by textbrowser** [comment]
SipHash is a cryptographic keyed hash. So, you can provide it a secret key and some secret (or public) value and produce a unique (within limits) memorable value. Smoke.pdf details the use of SipHash with respect to identifiers.

**Comment by textbrowser** [comment]
The hash is not important because it can be replaced. We know that aliases are usually short and we want to treat them like pseudo-secrets. One method of doing this is through key-derivation functions.

https://en.wikipedia.org/wiki/Key_derivation_function

By converting our aliases into keys, we can use the keys to transport our public keys to their desired destinations.

**Comment by textbrowser** [comment]
I have not forgotten the diagram. Many requests. :P
