### ISSUE TITLE
How to encrypt messages sent and received?

### ISSUE THREAD

**Issue by huutien98** [textbrowser/smoke#18]
I am not understanding the encryption mechanism of sending and receiving messages from the sender, this problem is quite complicated. I have read the code but don't understand. Please explain this to me, this is very important

**Comment by textbrowser** [comment]
This is directly from Smoke.odt. :) With some added comments.

CHAT
[PK] (1) // Encrypt your public-encryption-key digest using the destination's public-key. We do this so that the receiver can perform a speedy discovery of the person who sent the message. If the person is not known, the message is discarded. Of course, there is additional verification later.
{
	Sender's Public Encryption Key SHA-512 Digest (1)	64 Bytes
}

[AES-256] (2) // Encrypt a bunch of information using a previously-shared AES-256 key. Notice that there is a digital signature included. This digital signature is optional. If the receiver requires digital signatures, the message is discarded.
{
	0x00 (1)								1 Byte
	A Timestamp (2)							8 Bytes (Base-64)
	\n
	Message (3)								Variable (Base-64)
	\n
	Sequence (4)							8 Bytes (Base-64)
	\n
	Attachment (5)							Variable (Base-64)
	\n
	Message Identity (6)						64 Bytes (Base-64)
	\n
	[PK Signature] (7)						Variable (Base-64)
	{
		[PK] (1) || [AES-256] (1 ... 6) ||
		Recipient's Public Encryption Key SHA-512 Digest (1)
	}
}

[SHA-512 HMAC] (3)							64 Bytes // This is the digest of the two bundles above. If it is not valid, the message is discarded.
{
	[PK] || [AES-256] (1)
}

/*
** The destination is created via the recipient's Smoke Identity.
*/

[Destination SHA-512 HMAC] (4)					64 Bytes // This is a destination address. It allows Smoke Stack instances to direct traffic. It is ignored by other Echo machines. Even Smoke Stack instances may ignore it. If I remember correctly, Smoke tests this value before everything else to determine if you are the intended recipient. If you're not, message is discarded.
{
	[PK] || [AES-256] || [SHA-512 HMAC] (1)
}

Please note that by discarded I mean that the message could be echoed to another device. The source clarifies when this happens. For example, if the message is not for you, it is echoed (assuming you have multiple neighbors; it cannot be echoed to the sender if you have but one connection).

**Comment by textbrowser** [comment]
Order of operations in Smoke:
1. Am I the recipient? This is done via the destination.
2. I am the recipient. Decrypt the digest using my public-key. Do I know this person?
3. I know this person. Retrieve the HMAC digest key. Compute a digest of the first two bundles. Does the computed digest match the digest provided by the message?
4. The digests are identical? Decrypt the message bundle. Verify the signature, assuming we require it.
5. Valid signature? Good. We accept the message.

**Comment by textbrowser** [comment]
You can also open a discussion in Discussions for non-ticket items. These include questions, etc. Tickets are best left for errors and requests and translations and source changes.

**Comment by huutien98** [comment]
Thanks for the enthusiasm

**Comment by huutien98** [comment]
great team this is quite difficult but i will try to understand , can i ask more about the connection mechanism between smoke vs sport-on and how 2 users can recognize each other by smokeID ?

**Comment by huutien98** [comment]
great team this is quite difficult but i will try to understand , can i ask more about the connection mechanism between smoke vs sport-on and how 2 users can recognize each other by smokeID ?

**Comment by huutien98** [comment]
So when were the keys and digital signatures sent?

**Comment by textbrowser** [comment]
> Thanks for the enthusiasm

Do I appear enthusiastic? You're mistaken. :)

**Comment by textbrowser** [comment]
> So when were the keys and digital signatures sent?



> great team this is quite difficult but i will try to understand , can i ask more about the connection mechanism between smoke vs sport-on and how 2 users can recognize each other by smokeID ?

Which team? Spot-On and Smoke are compatible with Fire only. Smoke is a lighter evolved version of Spot-On. Both work with echo devices.

**Comment by textbrowser** [comment]
> So when were the keys and digital signatures sent?

When two devices are paired. They can be manually exchanged or exchanged via Smoke. Smoke periodically broadcasts keys to participants which have not been paired. Two people should pair each other so not to create noise. :)

**Comment by huutien98** [comment]
I use 2 smokes and connect to 1 sport-on and use the messaging function. is this correct?

**Comment by huutien98** [comment]
> > So when were the keys and digital signatures sent?
> 
> When two devices are paired. They can be manually exchanged or exchanged via Smoke. Smoke periodically broadcasts keys to participants which have not been paired. Two people should pair each other so not to create noise. :)

hmmm I am not understanding 2 smoke creating 2 different siphash how can they be linked together?

**Comment by textbrowser** [comment]
> I use 2 smokes and connect to 1 sport-on and use the messaging function. is this correct?

Yes. That's one example. I've mentioned SmokeStack too. And you can also create echo links with popular Unix tools. There's a demonstration in the Discussions.

https://github.com/textbrowser/smoke/discussions/13

Are you doing this for a school project?

**Comment by textbrowser** [comment]
Then you should put in the effort and learn without me giving you the answers. :P

**Comment by huutien98** [comment]
if you help I can understand it better and complete it faster .

**Comment by textbrowser** [comment]
I can help with false information too. :)

**Comment by huutien98** [comment]
Don't do that, help me graduate

**Comment by textbrowser** [comment]
> > > So when were the keys and digital signatures sent?
> > 
> > 
> > When two devices are paired. They can be manually exchanged or exchanged via Smoke. Smoke periodically broadcasts keys to participants which have not been paired. Two people should pair each other so not to create noise. :)
> 
> hmmm I am not understanding 2 smoke creating 2 different siphash how can they be linked together?

They're not physically linked. The two Smoke instances have an artificial awareness of one another. Are you familiar with PGP? E-mail? I have your e-mail account and you have mine. We're paired. That's how Smoke works too.

**Comment by textbrowser** [comment]
The public keys are shared on pseudo-private channels using the aliases (which are transformed into keys) Pseudo-private because the aliases can be exchanged in e-mail. If you exchange the aliases secretly, the public-key exchange is more secretive. Not totally secretive because the aliases are usually small in length and SipHash is not the best hash for creating keys with. Regardless, there is also a zero-knowledge protocol included so you can verify one another by using information that only the two people would know. The zero-knowledge protocol is executed within the scope of the exchanged public-keys. The question then is, can someone interfere with the public-key-exchange protocol by submitting their keys instead of mine making you believe that they are me. Yes. Can they also replicate the secret with the zero-knowledge proof? Yes, rubber-hose cryptography or breaking of the protocol or breaking of Smoke.

**Comment by textbrowser** [comment]
All set? Happy?

**Comment by textbrowser** [comment]
Another happy smoker! Closing.

**Comment by huutien98** [comment]
hey textbrowser . I graduated . thanks for help , love you <3

**Comment by textbrowser** [comment]
Very cool and congratulations. Good luck in life!
