### ISSUE TITLE
Cross-platform compatibility ; Protocols ; Publicity

### ISSUE THREAD

**Issue by kekukui** [textbrowser/smoke#3]
**1.**  Why should we use an app like **Smoke** instead of **Riot**, **Jami**, or **Tox**?  (Aside from the noted feature differences, under what circumstances is the Echo protocol better than Matrix, Tox or some other DHT variant?  How does it compare in terms of reliability, bandwidth efficiency, CPU usage, routing delays, resistance to traffic analysis, et cetera?)

https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_protocols
https://en.wikipedia.org/wiki/Comparison_of_cross-platform_instant_messaging_clients

**2.**  Is there a Smoke equivalent on iOS?  (Most people would not be able to use this as a replacement for SMS until it works on both platforms.)

**3.**  I can appreciate the humor, but you need to write more meaningful descriptions on your repositories if you want to attract more users, testers & contributors.  Always be mindful of the fact that some visitors & contributors will not be native English speakers and may not understand English cultural references.  Dont pass up any opportunities here: one new user or developer in the right place can influence many others.  Small details matter because it is very difficult to convince the general public to stop using insecure communications tools:

https://www.popularmechanics.com/technology/security/a29789903/what-is-sms/
https://www.popularmechanics.com/technology/a29726341/texts-delayed-random/

**Comment by textbrowser** [comment]
1. Because it's Smoke. Smoke does not exist to convince people to use it. I like it and some other people like it. That's sufficient. The source is open and you're welcome to study it. Echo is open and you're welcome to analyze it. I don't have the resources to provide discrete data points on its reliability, strengths, weaknesses, and comparisons.

CPU usage depends on many factors. Number of clients, number of active participants, number of Fire channels, device characteristics, network traffic, other applications resident on the device, Android version, network performance. SmokeStack, Smoke’s cousin, provides CD (a means of decreasing the quantity of messages a particular device receives) and thus limits system utilization. It provides other services too. You can also criticize that project. :)

2. No. I don’t have the resources to purchase expensive devices. Development occurs on virtual machines and low-end Android computers.

3. My projects do not have a specific audience. Humor is wonderful. Colors are wonderful. Language is wonderful. If small details matter, why should I provide meaningful descriptions? Did you read the Smoke documentation? It has small and large details and these perhaps translate into substantial descriptions.

4. Smoke is unique and I’m not writing this because I made it. It’s cute and free. It’s friendly and constantly improved. I don’t have a team and people are always welcome to submit ideas. As for meaningful descriptions, I prefer quality over verbose nonsense. I’m not selling a product. I’m not attempting to convince an audience.

5. You can install both applications and test them if you’d like.

**Comment by kekukui** [comment]
> **You can also criticize that project.**

I was not trying to be adversarial -- just trying to understand the technology and mission because I am compiling information on private messaging systems as a public service.

https://docs.google.com/spreadsheets/d/1-UlA4-tslROBDS9IqHalWVztqZo7uxlCeKPQ-8uoFOU/edit#gid=0

I hope you will excuse the misunderstanding here, since it's rare to find a project of this type which does **_not_** have an intended audience:  Most similar projects are actively seeking collaborators, funding and publicity.  They also publish research papers and give lectures on protocol design.  And many volunteers are looking for guidance regarding what projects to work on.

I think you have answered my question satisfactorily, and the answer is that you are not trying to create something for large scale distribution or general public consumption.  No problem.  There is nothing wrong with experimental projects, I was just collecting data on the goals and development status of various P2P protocols and applications so people with limited resources can decide where they want to spend those resources.

> **No. I don’t have the resources to purchase expensive devices.**

I had no way of knowing that you are the sole developer of mobile applications which implement this protocol, and would never suggest that you purchase an iphone under those circumstances.

> **As for meaningful descriptions, I prefer quality over verbose nonsense.**

No offense intended, but I fail to see how stuff like this makes sense:

_"Spot-On is an interstellar dolphin-propelled science vessel sailing on the winds of chaos. Now with Ultra StarBeams!"_

**Comment by textbrowser** [comment]
Neither Smoke nor Spot-On are experimental. They are functional, stable. New functions are added and both projects are consistently improved. Of course the general or the private public can enjoy the projects. Otherwise, they'd be well-funded, private, constantly advertised, promoted, etc., etc., etc. Why does something require lectures and research papers? I think papers are interesting, but they're not essential. I can play networked chess through Spot-On and Spot-On doesn't have chess in it.

Also, this is a Smoke ticket. Spot-On is a science vessel.

I'm not offended. Criticism is welcome.

I'm not actively seeking collaboration and I'm not actively dissuading it because the projects are open, free, and public.

**Comment by textbrowser** [comment]
Thanks!

**Comment by textbrowser** [comment]
Completed.
