### ISSUE TITLE
readme leaves me wanting: what does smoke DO?

### ISSUE THREAD

**Issue by a-raccoon** [textbrowser/smoke#34]
Please explain this app to me like I'm a 12 year old, or the mother of a 12 year old, or like I'm someone who still plays Pokémon Go, or like I'm an anthropologist visiting from a neighboring timeline.

Can't use an app that doesn't explain what it does in plain language, and why it's useful to whom. How do you use this app the most, for what, why?

F-Droid user

**Comment by textbrowser** [comment]
Smoke attempts to be very open.

You can share files with friends and those friends can share the files you're sharing with their friends. A file may be shared with another person as you're receiving the file. That is, the file does not have to be completed.

You can message people in private rooms. Like IRC.

You can message individuals or groups of individuals.

You can share files with Unix programs.

You can verify the identities of people.

You don't need a telephone number to communicate. You may discover people via their aliases.

Smoke has a partner, SmokeStack. There, messages may be stored if a friend is offline. Stack stores public keys, it's also a key server.

Voice and video are not included because that's a lot of work for one person.

Some functions, Steam (file sharing), work and do not work because of the fragmented Android versions.

I sometimes use Smoke to write files to a Unix machine if I don't have Bluetooth or the USB interface is malfunctioning.

I send files to people, kind of rarely. Sometimes attachments.

Sometimes on restricted networks, I can communicate with friends. A ..... VPS1 ..... B ..... VPS2 ..... C. A and C can text because B connects VPS1 and VPS2. A and C cannot share a common VPS.

**Comment by textbrowser** [comment]
Stack offers private connections for authenticated participants.

**Comment by textbrowser** [comment]
Please open other tickets if you need to. Thanks.
