### ISSUE TITLE
UI: some toggle switches are inverted.

### ISSUE THREAD

**Issue by bbigras** [textbrowser/smoke#38]
some switches are shown as enabled when the thing is on the left side. and sometimes it's on the right side.

Maybe it's an RTL thing.

**Comment by bbigras** [comment]
The enabled toggle should point to the right

![Screenshot_20230404-102621](https://user-images.githubusercontent.com/24027/230178776-b0c2ff5f-03c0-4414-b0ef-e68bbcb566e9.png)

**Comment by textbrowser** [comment]
I see the problem. Because text is attached to the check box, its orientation is RTL. Otherwise, the orientation would be locale-specific, however, with some locales the text would be on the left and therefore the widgets would be misaligned.

![Screenshot_20230405_154826](https://user-images.githubusercontent.com/10701156/230190430-cd3b6c68-8ac4-48a8-97a5-cbb84a760357.png)

**Comment by textbrowser** [comment]
As you can see, modifying the states of the check boxes is more tedious when they are misaligned. I prefer the columnar layout instead of the scattered layout.

**Comment by bbigras** [comment]
Fair enough. thanks

**Comment by textbrowser** [comment]
If the switches are installed in their own layout managers, the labels can be replaced with individual text views and the text would be on the right while the switch orientation would be locale-specific.

**Comment by textbrowser** [comment]
There are twelve switches and Android Studio is super annoying. If you attach a new XML, I'll review and add it. :)
