### ISSUE TITLE
decoy pw and timer closing login

### ISSUE THREAD

**Issue by alexlenn** [textbrowser/smoke#41]
Hi,

Smoke seems to be a chat application with saving data in an encrypted container?!

In our group-testing we thought 

- it would be an interesting feature to have two login passwords, one for a hidden login to a different chat environment / container (kind of decoy pw, similar to VeraCrypt startup, needed considering law in France) 

- and probably a timer to close the application after X defined minutes, hours or days, in case the hardware is lost or rided.

Thanks for a consideration.

Alex

**Comment by textbrowser** [comment]
Smoke includes a lock screen. Some devices terminate the application regardless of the background service.

Profiles are like that and there was idea somewhere about them. Perhaps as a reminder somewhere. :)

**Comment by textbrowser** [comment]
Multiple profiles are a lot of work:
1. A hidden password would be either a derivative of the actual password or another input parameter. Another input parameter provides a visual hint that Smoke has hidden features. This makes the feature impractical. Since the feature has to be documented, it makes the feature impractical.
2. Assume that the feature is practical. Multiple profiles with large keys make the feature impossible to tolerate because the second profile has to have its own data. Whenever a new pair of PKI data are generated, the data must be generated for two profiles. This can take many, many minutes. I cannot tolerate many, many minutes. This would require yet another profile option.
3. A second profile must be functional. Smoke will fail happily with invalid data and these failures hint that some hidden behavior is present. A clever observer will notice this and again the feature is impractical.
4. Android has profiles / accounts. Have you considered this? I ask because you'll never respond.
5. An alternate smoke.db database is yet again difficult.

Your request is like having a Unix account withing another Unix account. It's not impossible but it's not easy or practical.

**Comment by textbrowser** [comment]
Silence. Closing.
