### ISSUE TITLE
Add Somke to catappult.io

### ISSUE THREAD

**Issue by bolzobrazil** [textbrowser/smoke#42]
while discontinuing the credit card deposit sign the app Smoke for catappult.io with developers keys and add it to many stores for download.

**Comment by textbrowser** [comment]
Available here and Droid. Too much work to maintain the Android varieties. Stack broke without any changes after updating Studio. Google is garbage and not worth writing Java software. QML and Qt are nicer, portable, and offer much more reliability. Android is a destination device and not a developer platform. It's a sucky framework because it intentionally breaks software through their careless releases. And it's being sued in the US for monopoly practices. It sucks in everything.
