### ISSUE TITLE
Forking Signal and Session Dev smoke

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [textbrowser/smoke#47]
Forking Signal and Session Development smoke
session is more advanced, it doesn't require a cell phone number or username.

Signal https://github.com/signalapp
Session https://github.com/oxen-io

Developing on a fork smoke requires 
no cell phone number
no username
no server.
Inherit the Signal and Session feature surpass

smoke might need a better new name: Singularity.

**Comment by textbrowser** [comment]
You need not a telephone number for Smoke. Smoke has aliases and identities for locating people. Servers are necessary for communicating with people. And the rest that is another story.

**Comment by Zig-Rust-Odin** [comment]
> You need not a telephone number for Smoke. Smoke has aliases and identities for locating people. Servers are necessary for communicating with people. And the rest that is another story.

I mean, there's no centralized server, 🫠it's like https://f-droid.org/packages/d.d.meshenger/

**Comment by textbrowser** [comment]
That is also true. Smoke offers Spot-On, SmokeStack, and Spot-On-Lite. The concept of centralization is absent because the communications are private, public, and both.

**Comment by Zig-Rust-Odin** [comment]
Smoke lacks a visually good GUI Signal or XMPP client, or you have better! This topic can be closed now!

**Comment by textbrowser** [comment]
Let's summarize.

1. Smoke does not require telephone numbers.
2. Smoke offers aliases and identities (SipHash). The concept of a username does not exist in Smoke. In order to communicate with someone, we initially need their alias or SipHash. These are required for exchanging public keys. Future sessions require the identities for directing data through Stacks and lessening the data burden on Smokes.
3. Smoke is able to connect to SmokeStack, Spot-On, and Spot-On-Lite. These services may be private, public, or both.
4. **Smoke needs a nicer interface.**

**Comment by textbrowser** [comment]
Thanks you for the ticket.
